[package]
name = "alexandria-core"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license-file = "../../LICENSE"
repository.workspace = true

[dependencies]
anyhow.workspace = true
argon2.workspace = true
chrono.workspace = true
epub.workspace = true
ffmpeg-next.workspace = true
jsonwebtoken.workspace = true
kamadak-exif.workspace = true
lofty.workspace = true
lopdf.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
sqlx.workspace = true
thiserror.workspace = true
tokio.workspace = true
toml.workspace = true
tracing.workspace = true
uuid.workspace = true
walkdir.workspace = true

[dev-dependencies]
image.workspace = true
little_exif.workspace = true
tempfile.workspace = true
tokio.workspace = true
toml.workspace = true
zip.workspace = true